# Generated by Django 3.2.16 on 2022-10-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourceprovider_resourceseeker_resourceseekerservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
