# Generated by Django 3.2.16 on 2022-10-11 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20221011_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprovider',
            name='alternate_phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resourceprovider',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resourceseeker',
            name='alternate_phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resourceseeker',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resourceseekerservices',
            name='alternate_phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resourceseekerservices',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
