# Generated by Django 3.2.16 on 2022-10-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20221018_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='doc_name_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='docs_urls_9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprovider',
            name='verified_9',
            field=models.BooleanField(default=False),
        ),
    ]
