# Generated by Django 3.2.16 on 2022-10-18 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20221018_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{0,12}$')]),
        ),
    ]
