# Generated by Django 3.2.16 on 2022-10-18 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number entered.', regex='^\\+?1?\\d{0,12}$')]),
        ),
    ]
