# Generated by Django 3.2.16 on 2022-10-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_skills_with_experience', models.TextField()),
                ('secondory_skills_with_experience', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalOverView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('years_of_experience', models.FloatField()),
                ('industry', models.CharField(max_length=255)),
                ('leadership_experience', models.BooleanField(default=False)),
                ('how_many_years', models.FloatField()),
                ('interested_secondary_positions', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
