# Generated by Django 3.2.16 on 2022-10-27 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resources', '0012_professionaloverview_skillranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVerifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardType', models.CharField(max_length=120)),
                ('CardId', models.CharField(max_length=12)),
                ('UserNname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrested', models.BooleanField(default=False)),
                ('next_process', models.BooleanField(default=False)),
                ('share_info', models.BooleanField(default=False)),
                ('alt_phone_number', models.CharField(blank=True, max_length=17)),
                ('wa_number', models.CharField(blank=True, max_length=17)),
                ('receiver', models.CharField(blank=True, max_length=400)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('date_joined', models.DateTimeField()),
                ('registered_region', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_job_seeker', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_job_provider', models.BooleanField(default=False)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_profile', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
